dist: trusty
addons:
  chrome: stable
language: php
php:
  - 7.1
  - 7.0
  - 5.6
before_install:
  - gem install mime-types --version "< 3"
  - google-chrome-stable --headless --disable-gpu --port=8888 https://github.com &
  - composer update
  - php vendor/bin/codecept build
script:
  - php vendor/bin/codecept run acceptance --env travis